const std = @import("std");

/// Token styling settings for syntax highlighting
pub const VSCodeTokenSettings = struct {
    foreground: ?[]const u8 = null,
    background: ?[]const u8 = null,
    fontStyle: ?[]const u8 = null,
};

pub const VSCodeTokenColor = struct {
    scope: []const []const u8,
    settings: VSCodeTokenSettings,
};

pub const VSCodeThemeColors = struct {
    @"editor.background": []const u8,
    @"editor.foreground": []const u8,
    foreground: []const u8,
    disabledForeground: []const u8,
    focusBorder: []const u8,
    descriptionForeground: []const u8,
    errorForeground: []const u8,
    @"icon.foreground": []const u8,
    @"widget.border": []const u8,
    @"selection.background": []const u8,
    @"sash.hoverBorder": []const u8,
    @"activityBar.background": []const u8,
    @"activityBar.foreground": []const u8,
    @"activityBar.activeBorder": []const u8,
    @"activityBarBadge.background": []const u8,
    @"activityBarBadge.foreground": []const u8,
    @"sideBar.background": []const u8,
    @"sideBar.foreground": []const u8,
    @"sideBar.border": []const u8,
    @"sideBarTitle.foreground": []const u8,
    @"statusBar.background": []const u8,
    @"statusBar.foreground": []const u8,
    @"statusBar.noFolderBackground": []const u8,
    @"statusBar.debuggingBackground": []const u8,
    @"titleBar.activeBackground": []const u8,
    @"titleBar.activeForeground": []const u8,
    @"titleBar.inactiveBackground": []const u8,
    @"titleBar.inactiveForeground": []const u8,
    @"tab.activeBackground": []const u8,
    @"tab.activeForeground": []const u8,
    @"tab.inactiveBackground": []const u8,
    @"tab.inactiveForeground": []const u8,
    @"tab.activeBorder": []const u8,
    @"tab.border": []const u8,
    @"editorGroupHeader.tabsBackground": []const u8,
    @"panel.background": []const u8,
    @"panel.border": []const u8,
    @"panelTitle.activeBorder": []const u8,
    @"terminal.foreground": []const u8,
    @"terminal.ansiBlack": []const u8,
    @"terminal.ansiRed": []const u8,
    @"terminal.ansiGreen": []const u8,
    @"terminal.ansiYellow": []const u8,
    @"terminal.ansiBlue": []const u8,
    @"terminal.ansiMagenta": []const u8,
    @"terminal.ansiCyan": []const u8,
    @"terminal.ansiWhite": []const u8,
    @"terminal.ansiBrightBlack": []const u8,
    @"terminal.ansiBrightRed": []const u8,
    @"terminal.ansiBrightGreen": []const u8,
    @"terminal.ansiBrightYellow": []const u8,
    @"terminal.ansiBrightBlue": []const u8,
    @"terminal.ansiBrightMagenta": []const u8,
    @"terminal.ansiBrightCyan": []const u8,
    @"terminal.ansiBrightWhite": []const u8,
    @"input.background": []const u8,
    @"input.border": []const u8,
    @"input.foreground": []const u8,
    @"input.placeholderForeground": []const u8,
    @"inputOption.activeBorder": []const u8,
    @"inputOption.activeBackground": []const u8,
    @"inputOption.activeForeground": []const u8,
    @"inputValidation.errorBackground": []const u8,
    @"inputValidation.errorBorder": []const u8,
    @"inputValidation.errorForeground": []const u8,
    @"inputValidation.warningBackground": []const u8,
    @"inputValidation.warningBorder": []const u8,
    @"inputValidation.warningForeground": []const u8,
    @"inputValidation.infoBackground": []const u8,
    @"inputValidation.infoBorder": []const u8,
    @"inputValidation.infoForeground": []const u8,
    @"dropdown.background": []const u8,
    @"dropdown.foreground": []const u8,
    @"dropdown.border": []const u8,
    @"dropdown.listBackground": []const u8,
    @"quickInput.background": []const u8,
    @"quickInput.foreground": []const u8,
    @"quickInputList.focusBackground": []const u8,
    @"quickInputList.focusForeground": []const u8,
    @"quickInputList.focusIconForeground": []const u8,
    @"quickInputTitle.background": []const u8,
    @"list.activeSelectionBackground": []const u8,
    @"list.activeSelectionForeground": []const u8,
    @"list.inactiveSelectionBackground": []const u8,
    @"list.hoverBackground": []const u8,
    @"list.focusBackground": []const u8,
    @"list.highlightForeground": []const u8,
    @"pickerGroup.foreground": []const u8,
    @"pickerGroup.border": []const u8,
    @"button.background": []const u8,
    @"button.foreground": []const u8,
    @"button.hoverBackground": []const u8,
    @"button.secondaryBackground": []const u8,
    @"button.secondaryForeground": []const u8,
    @"button.secondaryHoverBackground": []const u8,
    @"badge.background": []const u8,
    @"badge.foreground": []const u8,
    @"breadcrumb.foreground": []const u8,
    @"breadcrumb.focusForeground": []const u8,
    @"breadcrumb.activeSelectionForeground": []const u8,
    @"breadcrumb.background": []const u8,
    @"scrollbarSlider.background": []const u8,
    @"scrollbarSlider.hoverBackground": []const u8,
    @"scrollbarSlider.activeBackground": []const u8,
    @"editorLineNumber.foreground": []const u8,
    @"editorLineNumber.activeForeground": []const u8,
    @"editorCursor.foreground": []const u8,
    @"editor.selectionBackground": []const u8,
    @"editor.inactiveSelectionBackground": []const u8,
    @"editor.findMatchBackground": []const u8,
    @"editor.findMatchHighlightBackground": []const u8,
    @"editorBracketMatch.background": []const u8,
    @"editorBracketMatch.border": []const u8,
    @"editorBracketHighlight.foreground1": []const u8,
    @"editorBracketHighlight.foreground2": []const u8,
    @"editorBracketHighlight.foreground3": []const u8,
    @"editorBracketHighlight.foreground4": []const u8,
    @"editorBracketHighlight.foreground5": []const u8,
    @"editorBracketHighlight.foreground6": []const u8,
    @"editorBracketPairGuide.activeBackground1": []const u8,
    @"editorBracketPairGuide.activeBackground2": []const u8,
    @"editorBracketPairGuide.activeBackground3": []const u8,
    @"editorBracketPairGuide.activeBackground4": []const u8,
    @"editorBracketPairGuide.activeBackground5": []const u8,
    @"editorBracketPairGuide.activeBackground6": []const u8,
    @"editorBracketPairGuide.background1": []const u8,
    @"editorBracketPairGuide.background2": []const u8,
    @"editorBracketPairGuide.background3": []const u8,
    @"editorBracketPairGuide.background4": []const u8,
    @"editorBracketPairGuide.background5": []const u8,
    @"editorBracketPairGuide.background6": []const u8,
    @"editorWhitespace.foreground": []const u8,
    @"editorWidget.background": []const u8,
    @"editorWidget.foreground": []const u8,
    @"editorWidget.border": []const u8,
    @"editorWidget.resizeBorder": []const u8,
    @"editorSuggestWidget.background": []const u8,
    @"editorSuggestWidget.foreground": []const u8,
    @"editorSuggestWidget.border": []const u8,
    @"editorSuggestWidget.highlightForeground": []const u8,
    @"editorSuggestWidget.focusHighlightForeground": []const u8,
    @"editorSuggestWidget.selectedBackground": []const u8,
    @"editorSuggestWidget.selectedForeground": []const u8,
    @"editorSuggestWidget.selectedIconForeground": []const u8,
    @"editorHoverWidget.background": []const u8,
    @"editorHoverWidget.foreground": []const u8,
    @"editorHoverWidget.border": []const u8,
    @"editorHoverWidget.highlightForeground": []const u8,
    @"editorHoverWidget.statusBarBackground": []const u8,
    @"editorError.foreground": []const u8,
    @"editorWarning.foreground": []const u8,
    @"editorInfo.foreground": []const u8,
    @"editorGutter.addedBackground": []const u8,
    @"editorGutter.modifiedBackground": []const u8,
    @"editorGutter.deletedBackground": []const u8,
    @"gitDecoration.addedResourceForeground": []const u8,
    @"gitDecoration.modifiedResourceForeground": []const u8,
    @"gitDecoration.deletedResourceForeground": []const u8,
    @"gitDecoration.untrackedResourceForeground": []const u8,
    @"gitDecoration.ignoredResourceForeground": []const u8,
    @"peekView.border": []const u8,
    @"peekViewEditor.background": []const u8,
    @"peekViewResult.background": []const u8,
    @"peekViewTitle.background": []const u8,
    @"notificationCenter.border": []const u8,
    @"notificationCenterHeader.background": []const u8,
    @"notifications.background": []const u8,
    @"notifications.border": []const u8,
    @"notificationLink.foreground": []const u8,
    @"settings.headerForeground": []const u8,
    @"settings.modifiedItemIndicator": []const u8,
    @"settings.focusedRowBackground": []const u8,
    @"settings.rowHoverBackground": []const u8,
    @"settings.focusedRowBorder": []const u8,
    @"settings.numberInputBackground": []const u8,
    @"settings.numberInputForeground": []const u8,
    @"settings.numberInputBorder": []const u8,
    @"settings.textInputBackground": []const u8,
    @"settings.textInputForeground": []const u8,
    @"settings.textInputBorder": []const u8,
    @"settings.checkboxBackground": []const u8,
    @"settings.checkboxForeground": []const u8,
    @"settings.checkboxBorder": []const u8,
    @"settings.dropdownBackground": []const u8,
    @"settings.dropdownForeground": []const u8,
    @"settings.dropdownBorder": []const u8,
    @"settings.dropdownListBorder": []const u8,
    @"textLink.foreground": []const u8,
    @"textLink.activeForeground": []const u8,
    @"textBlockQuote.background": []const u8,
    @"textBlockQuote.border": []const u8,
    @"textCodeBlock.background": []const u8,
    @"textPreformat.foreground": []const u8,
    @"textSeparator.foreground": []const u8,
    @"walkThrough.embeddedEditorBackground": []const u8,
    @"welcomePage.background": []const u8,
};

pub const ThemeType = enum {
    dark,
    light,
};

// Complete VSCode theme structure
pub const VSCodeTheme = struct {
    @"$schema": []const u8,
    name: []const u8,
    type: ThemeType,
    colors: VSCodeThemeColors,
    tokenColors: []const VSCodeTokenColor,
};
